import {
  LayoutGrid,
  Search,
  Brain,
  Radar,
  MessageSquare,
  GraduationCap,
  TrendingUp,
  Scan,
  Sparkles,
  Rocket,
  Target,
  Smartphone,
  Headphones,
  Wifi,
  Activity,
  Wallet,
  Globe,
  Link2,
  FileText,
  MapPin,
  ShieldCheck,
  Repeat,
  Megaphone,
  type LucideIcon,
} from "lucide-react";
import type { NavIconName } from "@/config/navigation.config";

const ICON_MAP: Record<NavIconName | "Target" | "Smartphone", LucideIcon> = {
  LayoutGrid,
  Search,
  Brain,
  Radar,
  MessageSquare,
  GraduationCap,
  TrendingUp,
  Scan,
  Sparkles,
  Rocket,
  Target,
  Smartphone,
  Headphones,
  Wifi,
  Activity,
  Wallet,
  Globe,
  Link2,
  FileText,
  MapPin,
  ShieldCheck,
  Repeat,
  Megaphone,
};

export function getNavIcon(name: string): LucideIcon {
  return ICON_MAP[name as keyof typeof ICON_MAP] ?? Target;
}
